CREATE DATABASE IF NOT EXISTS cargo_db
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cargo_db;

-- 1. KHACH_HANG
CREATE TABLE KHACH_HANG (
    ID_KH    VARCHAR(10)  NOT NULL,
    TEN_KH   VARCHAR(100) NOT NULL,
    EMAIL    VARCHAR(100) UNIQUE,
    SDT      VARCHAR(15)  NOT NULL,
    DIA_CHI  VARCHAR(200) NOT NULL,
    CONSTRAINT PK_KHACH_HANG PRIMARY KEY (ID_KH)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. HOA_DON (khai bao truoc DON_HANG vi DON_HANG co FK tro sang)
CREATE TABLE HOA_DON (
    ID_HD                  VARCHAR(10) NOT NULL,
    THOI_GIAN_TAO          DATETIME    NOT NULL,
    THOI_GIAN_HOAN_THANH   DATETIME    NULL,
    TRANG_THAI             VARCHAR(50) NOT NULL,
    CONSTRAINT PK_HOA_DON  PRIMARY KEY (ID_HD),
    CONSTRAINT CK_HD_TT    CHECK (TRANG_THAI IN
        ('Chua thanh toan','Da thanh toan')),
    CONSTRAINT CK_HD_TGIAN CHECK (
        THOI_GIAN_HOAN_THANH IS NULL OR
        THOI_GIAN_HOAN_THANH > THOI_GIAN_TAO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. LO_TRINH
CREATE TABLE LO_TRINH (
    ID_LT       VARCHAR(10)  NOT NULL,
    TEN_LT      VARCHAR(200) NOT NULL,
    TRANG_THAI  VARCHAR(50)  NOT NULL,
    CONSTRAINT PK_LO_TRINH PRIMARY KEY (ID_LT),
    CONSTRAINT CK_LT_TT CHECK (TRANG_THAI IN
        ('Dang hoat dong','Tam dung'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. DON_HANG
CREATE TABLE DON_HANG (
    ID_DH        VARCHAR(10)   NOT NULL,
    KHOI_LUONG   DECIMAL(10,2) NOT NULL,
    QUANG_DUONG  DECIMAL(10,2) NOT NULL,
    TRANG_THAI   VARCHAR(50)   NOT NULL,
    THANH_TIEN   DECIMAL(15,2) NOT NULL,
    ID_KH_GUI    VARCHAR(10)   NOT NULL,
    ID_KH_NHAN   VARCHAR(10)   NOT NULL,
    ID_LT        VARCHAR(10)   NOT NULL,
    ID_HD        VARCHAR(10)   NULL,
    CONSTRAINT PK_DON_HANG    PRIMARY KEY (ID_DH),
    CONSTRAINT FK_DH_KH_GUI   FOREIGN KEY (ID_KH_GUI)
        REFERENCES KHACH_HANG(ID_KH)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FK_DH_KH_NHAN  FOREIGN KEY (ID_KH_NHAN)
        REFERENCES KHACH_HANG(ID_KH)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FK_DH_LT       FOREIGN KEY (ID_LT)
        REFERENCES LO_TRINH(ID_LT)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FK_DH_HD       FOREIGN KEY (ID_HD)
        REFERENCES HOA_DON(ID_HD)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT CK_DH_TT  CHECK (TRANG_THAI IN (
        'Cho xu ly','Dang van chuyen','Da giao','Hoan tra')),
    CONSTRAINT CK_DH_KL  CHECK (KHOI_LUONG  > 0),
    CONSTRAINT CK_DH_QD  CHECK (QUANG_DUONG > 0),
    CONSTRAINT CK_DH_TH  CHECK (THANH_TIEN >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. DIEM_TRUNG_CHUYEN
CREATE TABLE DIEM_TRUNG_CHUYEN (
    ID_DTC              VARCHAR(10)  NOT NULL,
    TEN_DTC             VARCHAR(100) NOT NULL,
    DIA_CHI             VARCHAR(200) NOT NULL,
    THOI_GIAN_LAY_HANG  VARCHAR(50)  NULL,
    CONSTRAINT PK_DTC PRIMARY KEY (ID_DTC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. CHANG_DUONG
CREATE TABLE CHANG_DUONG (
    ID_CD      VARCHAR(10) NOT NULL,
    STT        INT         NOT NULL,
    ID_LT      VARCHAR(10) NOT NULL,
    ID_DTC_BD  VARCHAR(10) NOT NULL,
    ID_DTC_KT  VARCHAR(10) NOT NULL,
    CONSTRAINT PK_CHANG_DUONG PRIMARY KEY (ID_CD),
    CONSTRAINT UQ_CD_LT_STT  UNIQUE (ID_LT, STT),
    CONSTRAINT FK_CD_LT      FOREIGN KEY (ID_LT)
        REFERENCES LO_TRINH(ID_LT)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FK_CD_DTC_BD  FOREIGN KEY (ID_DTC_BD)
        REFERENCES DIEM_TRUNG_CHUYEN(ID_DTC)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_CD_DTC_KT  FOREIGN KEY (ID_DTC_KT)
        REFERENCES DIEM_TRUNG_CHUYEN(ID_DTC)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT CK_CD_STT CHECK (STT > 0),
    CONSTRAINT CK_CD_DTC CHECK (ID_DTC_BD <> ID_DTC_KT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. PHUONG_TIEN
CREATE TABLE PHUONG_TIEN (
    BIEN_SO     VARCHAR(15)   NOT NULL,
    LOAI_PT     VARCHAR(50)   NOT NULL,
    TRONG_TAI   DECIMAL(10,2) NOT NULL,
    TRANG_THAI  VARCHAR(50)   NOT NULL,
    CONSTRAINT PK_PHUONG_TIEN PRIMARY KEY (BIEN_SO),
    CONSTRAINT CK_PT_TT CHECK (TRANG_THAI IN ('Hoat dong','Bao tri')),
    CONSTRAINT CK_PT_TL CHECK (TRONG_TAI > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 8. NHAN_VIEN_GIAO_HANG
CREATE TABLE NHAN_VIEN_GIAO_HANG (
    ID_NV    VARCHAR(10)  NOT NULL,
    TEN_NV   VARCHAR(100) NOT NULL,
    SDT      VARCHAR(15)  NOT NULL UNIQUE,
    EMAIL    VARCHAR(100) UNIQUE,
    DIA_CHI  VARCHAR(200) NULL,
    CONSTRAINT PK_NHAN_VIEN PRIMARY KEY (ID_NV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 9. PHAN_CONG
CREATE TABLE PHAN_CONG (
    ID_PC   VARCHAR(10)  NOT NULL,
    CA_LAM  VARCHAR(100) NOT NULL,
    ID_CD   VARCHAR(10)  NOT NULL,
    ID_NV   VARCHAR(10)  NOT NULL,
    BIEN_SO VARCHAR(15)  NOT NULL,
    CONSTRAINT PK_PHAN_CONG PRIMARY KEY (ID_PC),
    CONSTRAINT FK_PC_CD  FOREIGN KEY (ID_CD)
        REFERENCES CHANG_DUONG(ID_CD)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FK_PC_NV  FOREIGN KEY (ID_NV)
        REFERENCES NHAN_VIEN_GIAO_HANG(ID_NV)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FK_PC_PT  FOREIGN KEY (BIEN_SO)
        REFERENCES PHUONG_TIEN(BIEN_SO)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 10. CHI_TIET_VAN_DON
CREATE TABLE CHI_TIET_VAN_DON (
    ID_VD                VARCHAR(10) NOT NULL,
    TRANG_THAI           VARCHAR(50) NOT NULL,
    THOI_GIAN_NHAN_HANG  DATETIME    NULL,
    THOI_GIAN_GIAO_HANG  DATETIME    NULL,
    ID_DH                VARCHAR(10) NOT NULL,
    ID_PC                VARCHAR(10) NOT NULL,
    CONSTRAINT PK_CHI_TIET_VAN_DON PRIMARY KEY (ID_VD),
    CONSTRAINT UQ_VD_DH_PC         UNIQUE (ID_DH, ID_PC),
    CONSTRAINT FK_VD_DH  FOREIGN KEY (ID_DH)
        REFERENCES DON_HANG(ID_DH)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FK_VD_PC  FOREIGN KEY (ID_PC)
        REFERENCES PHAN_CONG(ID_PC)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT CK_VD_TT   CHECK (TRANG_THAI IN (
        'Dang van chuyen','Da giao','Hoan tra')),
    CONSTRAINT CK_VD_TGIAN CHECK (
        THOI_GIAN_GIAO_HANG IS NULL OR
        THOI_GIAN_NHAN_HANG IS NULL OR
        THOI_GIAN_GIAO_HANG > THOI_GIAN_NHAN_HANG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;