-- Bước 1: Tắt cơ chế kiểm tra khóa ngoại
SET FOREIGN_KEY_CHECKS = 0;

-- Bước 2: Xóa sạch dữ liệu của từng bảng
TRUNCATE TABLE CHI_TIET_VAN_DON;
TRUNCATE TABLE PHAN_CONG;
TRUNCATE TABLE CHANG_DUONG;
TRUNCATE TABLE DON_HANG;
TRUNCATE TABLE NHAN_VIEN_GIAO_HANG;
TRUNCATE TABLE PHUONG_TIEN;
TRUNCATE TABLE DIEM_TRUNG_CHUYEN;
TRUNCATE TABLE LO_TRINH;
TRUNCATE TABLE HOA_DON;
TRUNCATE TABLE KHACH_HANG;

-- Bước 3: Bật lại cơ chế kiểm tra khóa ngoại để bảo vệ database
SET FOREIGN_KEY_CHECKS = 1;